apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  labels:
    app: backend
spec:
  serviceName: backend
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: localhost/k8s-training-backend:v1.0.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 56Mi
