apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP # Schritt 3: testweise auf NodePort patchen
  selector:
    app: __TODO_LABEL_WERT__ # muss zu den Pod-Labels des Deployments passen
  ports:
    - port: 80
      targetPort: __TODO_CONTAINER_PORT__ # z. B. 8080
